version: '3'

services:
  app:
    build: 
      context: ./bot_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

# volumes:
#     postgres-data: {}

